name: 'Generate String'
description: 'Generates a string from the given input'
env:
  DEFAULT_INPUT: 'No string provided'
inputs:
  given_input:
    description: 'The input given'
    required: false
    default: $DEFAULT_INPUT
outputs:
  string:
    description: 'generated string'
    value: ${{  }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: |
        string=$(( $inputs.given_input == '' ? $DEFAULT_INPUT : $inputs.given_input ))
        echo "$string"
      shell: bash
