name: 'Generate String'
description: 'Generates a string from the given input'
env: 
  DEFAULT_STRING: No string provided
  OUTPUT_STRING: Default output string
inputs:
  given_input:
    description: 'The input given'
    required: false
    default: DEFAULT_STRING
outputs:
  string:
    description: 'generated string'
    value: $OUTPUT_STRING
runs:
  using: "composite"
  steps:
    - run: echo "string=${{ inputs.given_input }} not empty" >> $env.OUTPUT_STRING     
      shell: bash
      if: ${{ inputs.given_input != '' }}
      
      #outputting a deafault string if we're given an empty string-- I want empty strings to be treated as no input
    - run: echo "string=$DEFAULT_STRING" >> $OUTPUT_STRING
      shell: bash
      if: ${{ inputs.given_input == '' }}
      
