name: 'Generate String'
description: 'Generates a string from the given input'
env:
  DEFAULT_INPUT: 'No string provided'
inputs:
  given_input:
    description: 'The input given'
    required: false
    default: $DEFAULT_INPUT
outputs:
  string:
    description: 'generated string'
    value: ${{ steps.step1.outputs.string }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: |
        string=$([ ${{ inputs.given_input }}== ] && echo ${{ DEFAULT_INPUT }} || echo ${{ inputs.given_input }} )
        echo "$string"
        echo "string=$string" >> $GITHUB_OUTPUT
      shell: bash
