name: 'Generate String'
description: 'Generates a string from the given input'
inputs:
  given_input:
    description: 'The input given'
    required: false
    default: "No input given"
outputs:
  string:
    description: 'generated string'
    value: ${{ steps.step1.outputs.string }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: |
        echo ${{ inputs.given_input.default }}
        string=$([ ${{ inputs.given_input }}== ] && echo "No input given -- empty input" || echo ${{ inputs.given_input }} )
        echo "string=$string" >> $GITHUB_OUTPUT
      shell: bash
