name: 'Generate String'
description: 'Generates a string from the given input'
inputs:
  given_input:
    description: 'The input given'
    required: false
    default: 'No string provided'
outputs:
  string:
    description: 'generated string'
    value: ${{ steps.step1.outputs.string }}
runs:
  using: "composite"
  steps:
    - run: echo "string=${{ inputs.given_input }} was given" >> $GITHUB_OUTPUT
      id: step1
      shell: bash
